CREATE ROLE pngie_app WITH LOGIN PASSWORD ':NI=CcM#D.jL(i#ni1v&[^qU';
GRANT CONNECT ON DATABASE pngie_rdc TO pngie_app;
GRANT USAGE ON SCHEMA public TO pngie_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO pngie_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO pngie_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pngie_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO pngie_app;